CREATE TABLE IF NOT EXISTS public.filiais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filial TEXT NOT NULL,
  cnpj TEXT,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.filiais ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "filiais_select" ON public.filiais;
CREATE POLICY "filiais_select" ON public.filiais
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "filiais_insert" ON public.filiais;
CREATE POLICY "filiais_insert" ON public.filiais
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "filiais_update" ON public.filiais;
CREATE POLICY "filiais_update" ON public.filiais
  FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "filiais_delete" ON public.filiais;
CREATE POLICY "filiais_delete" ON public.filiais
  FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS filiais_user_id_idx ON public.filiais(user_id);
